# Generated by Django 3.0.8 on 2020-07-02 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20200702_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='notes', to='notes.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
